W0626 14:10:31.907805 16244 torch\distributed\elastic\multiprocessing\redirects.py:27] NOTE: Redirects are currently not supported in Windows or MacOs.
W0626 14:10:31.939049 16244 torch\distributed\run.py:757]
W0626 14:10:31.939049 16244 torch\distributed\run.py:757] *****************************************
W0626 14:10:31.939049 16244 torch\distributed\run.py:757] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
W0626 14:10:31.939049 16244 torch\distributed\run.py:757] *****************************************
C:C\:\UserUsers\s\aabrebreh\AppDath\aAp\pLoDatca\aLlocal\P\rogPrograms\Pyrams\Pytthon\Pyhon\Python39\pytthon.hC:oe\nxUse3e:9r \scp\ayantb'hrt eh\oCoAppData\:\UsC:\Uers\anpLsb.eoerencasx rl\e: can'ePf\t riah\olboAge perr'pnaeDp mh:Dfs\\ai\AttlPppaeyrD\ taaL'hntoDona\:\\cLsfPaotrylcoatC\arnhoPlms:nrC\ef\3o:ProU9g\r\rs\rUoSmepasgperymerir\tsraksSh\s\e-DoPma\prnysbaii.thrbkveC\oere-x:Pn\eeDriven-n-\yhPhTeTrt\y\r:UahAtAa snonhpnsesp\opcarfpPnDformer-39\pythVnsoryao2'\Dmttn\taaera.m bth-V2\main\eaorao_finpe\nLxieehLoocatun3cenln\e9\p_f A.a:y\ifppy': [Errno 2netune.py': [ErpData]irno 2] le tP\ Nl 'hrLNo\cDoooo Pa:ngc srn\.rasuo'teamucgtrxlschr ae\\h aon:PP fmps ryfisefcotil\noaghleP rnroe yfm'an otile 'D:\transfoetm\orhrr sPr om\o\y dneSpPtdi\rpeyhirP\intoreytk hnecShefo3ctpo-in9toinDl\\ork3rePprye9i yyy
-Driven-Transfv'tt
\oeDhhprn:ooym-\traernntnT-3.esrV9hxfor\oeanmpn:2\ey. sfr\ecmaiSxaotnpenrh_i:'merke-Dfi tor-ne niVctopv2an'eenuntn fie.\m.le -Trapyae n'': [ED:xosfi\eprorm:ernte nn_rrc ofa-afilnVn ies2'2n f\t e'om]otDrm pu:aereneiN\n\.noSpip_  tkyfsfre'iuia-:nclnD ehesf[t  roEufiirrn'lvereDemnn.: e-Tpy':o 2or r\] \Sanr [EtrNopisadirrfnsrkno former\Sp 2ecoik]etrse -omu-NDrecDoryrhr i
-Vivve2\enn-ma-TTrinraan_fnssfinfooretrme fsur-ilchV2e  f\morilai de n_fiouimer rerndicte.reorpyctor'ne-V: tu2\[Enemarr.yin_finetune.pynp
y
oy':'  : [E[Errrrnon2]  o 2No 2] No s]sucu Nchoh f  ilsfeuch fi or direlicelt eoo orry
r dire ctordiyr
ectory
E0626 14:10:38.888521 16244 torch\distributed\elastic\multiprocessing\api.py:826] failed (exitcode: 2) local_rank: 0 (pid: 3100) of binary: D:\transformer\Spike-Driven-Transformer-V2\myenv\Scripts\python.exe
Traceback (most recent call last):
  File "C:\Users\abreh\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\abreh\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\transformer\Spike-Driven-Transformer-V2\myenv\Scripts\torchrun.exe\__main__.py", line 7, in <module>
  File "D:\transformer\Spike-Driven-Transformer-V2\myenv\lib\site-packages\torch\distributed\elastic\multiprocessing\errors\__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "D:\transformer\Spike-Driven-Transformer-V2\myenv\lib\site-packages\torch\distributed\run.py", line 879, in main
    run(args)
  File "D:\transformer\Spike-Driven-Transformer-V2\myenv\lib\site-packages\torch\distributed\run.py", line 870, in run
    elastic_launch(
  File "D:\transformer\Spike-Driven-Transformer-V2\myenv\lib\site-packages\torch\distributed\launcher\api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "D:\transformer\Spike-Driven-Transformer-V2\myenv\lib\site-packages\torch\distributed\launcher\api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
main_finetune.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-06-26_14:10:38
  host      : DESKTOP-E859SOQ
  rank      : 1 (local_rank: 1)
  exitcode  : 2 (pid: 19928)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-06-26_14:10:38
  host      : DESKTOP-E859SOQ
  rank      : 2 (local_rank: 2)
  exitcode  : 2 (pid: 22208)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-06-26_14:10:38
  host      : DESKTOP-E859SOQ
  rank      : 3 (local_rank: 3)
  exitcode  : 2 (pid: 9580)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[4]:
  time      : 2024-06-26_14:10:38
  host      : DESKTOP-E859SOQ
  rank      : 4 (local_rank: 4)
  exitcode  : 2 (pid: 2012)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[5]:
  time      : 2024-06-26_14:10:38
  host      : DESKTOP-E859SOQ
  rank      : 5 (local_rank: 5)
  exitcode  : 2 (pid: 20224)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[6]:
  time      : 2024-06-26_14:10:38
  host      : DESKTOP-E859SOQ
  rank      : 6 (local_rank: 6)
  exitcode  : 2 (pid: 21584)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[7]:
  time      : 2024-06-26_14:10:38
  host      : DESKTOP-E859SOQ
  rank      : 7 (local_rank: 7)
  exitcode  : 2 (pid: 21024)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-06-26_14:10:38
  host      : DESKTOP-E859SOQ
  rank      : 0 (local_rank: 0)
  exitcode  : 2 (pid: 3100)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
